210 - Fixed AB:6638693 NoMethodError: undefined method `rating_descriptor' for nil:NilClass. I fixed the view, so that it does not break, and also the ActivityObserver's before_destroy method to be correctly delete the Activity when it exsists. The previous specs did not catch this, due to the activity factory having set a hard coded item_id